# Fastfile for F-Droid metadata generation

default_platform(:android)

platform :android do
  desc "Generate F-Droid metadata"
  lane :fdroid_metadata do
    # This lane can be used to generate or update metadata for F-Droid
    # Currently, metadata is manually maintained in fastlane/metadata/android/en-US/
  end
end